feat: add get_image for all DocItem
docling-project/docling-core pull request #67
Opened 2024-11-12 15:33 UTC by sh-gupta

We want the `image` attribute to be available for `TextItem` to allow exposing equation images. I have moved `image` from `FloatingItem` to `DocItem` so that it becomes part of `TextItem` as well.

Related issue: [https://github.com/DS4SD/docling/issues/299](https://github.com/DS4SD/docling/issues/299)

2024-11-12 16:35 UTC, vagenas requested changes
@sh-gupta @cau-git ⚠️  note that any changes to the subtypes of DoclingDocument:
1. Need to be backwards compatible within docling-core 2.x.y, e.g. new field with default value, and
2. then imply a new minor version bump of the DoclingDocument as well as potentially DocMeta which also depends on the DocItem.

2024-11-13 13:24 UTC, PeterStaar-IBM commented
@sh-gupta We quickly discussed, we need to do the following points (@cau-git will explain),

- add get_image to DocItem (overloaded on PictureItem)
	- check if there are page-images
- enrichment models can leverage the backend
- deprecate this: https://github.com/DS4SD/docling/blob/main/docling/datamodel/pipeline_options.py#L84C5-L84C28

2024-11-14 15:43 UTC, sh-gupta commented
Made the required changes:
1. Moved `image` from `DocItem` back to `FloatingItem`
2. Added `get_image` function to `DocItem`. If returns `None` if provenance is not found or page image is not available, else it returns an appropriately cropped section of the page image
3. Overrode `get_image` in `FloatingItem`

2024-11-14 18:04 UTC, cau-git commented
> Made the required changes:
> 
> 1. Moved `image` from `DocItem` back to `FloatingItem`
> 2. Added `get_image` function to `DocItem`. If returns `None` if provenance is not found or page image is not available, else it returns an appropriately cropped section of the page image
> 3. Overrode `get_image` in `FloatingItem`

This looks good now, thanks!

2024-11-15 06:29 UTC, PeterStaar-IBM commented
@sh-gupta Could we add some unit-tests for this functionality?

2024-11-15 13:50 UTC, dolfim-ibm approved these changes

2024-11-15 14:17 UTC, PeterStaar-IBM approved these changes
very nice!

2024-11-16 15:19 UTC, sh-gupta commented
@PeterStaar-IBM : I've added tests for `DocItem.get_image` and `FloatingItem.get_image`

@dolfim-ibm : I initially thought raising an error but then decided to stick with `None` to be consistent with the behavior of `FloatingItem.image` when `image` is not found. I can raise an exception if you prefer.

@vagenas : I've made the changes as per your discussion. Can you please take a look?

2024-11-17 10:42 UTC, PeterStaar-IBM approved these changes
Lovely! Time to get this in!

2024-11-17 15:28 UTC, vagenas commented
@sh-gupta in the docstring of the two `get_image()` methods, I would explicitly add that the method returns `None` if no image is available / applicable (exact wording up to you, but just to mention that `None` is returned "otherwise").

2024-11-18 11:45 UTC, PeterStaar-IBM approved these changes
super!

2024-11-18 12:33 UTC, dolfim-ibm approved these changes

2024-11-18 12:34 UTC, merged